"""Add description field to children

Revision ID: e946ff3047dc
Revises: 17163de390f8
Create Date: 2025-12-13 22:44:21.338810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e946ff3047dc'
down_revision: Union[str, None] = '17163de390f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'description')
    # ### end Alembic commands ###
